services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: crewuser
      POSTGRES_PASSWORD: crewpass
      POSTGRES_DB: crewdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U crewuser -d crewdb"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  backend:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
      - media_data:/app/media
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./backend/.env
    restart: unless-stopped

volumes:
  postgres_data:
  media_data:
