# Generated by Django 5.1.7 on 2025-07-23 17:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crew_sheets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='crewsheet',
            name='confidence_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='crewsheet',
            name='needs_review',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='crewsheet',
            name='quality_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.CreateModel(
            name='ExtractionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('raw_extraction', models.JSONField()),
                ('processed_extraction', models.JSONField()),
                ('final_data', models.JSONField(blank=True, null=True)),
                ('extraction_time_seconds', models.FloatField(default=0.0)),
                ('api_cost_estimate', models.FloatField(default=0.0)),
                ('token_usage', models.JSONField(default=dict)),
                ('user_satisfaction_score', models.FloatField(blank=True, null=True)),
                ('edit_ratio', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('crew_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extraction_logs', to='crew_sheets.crewsheet')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExtractionSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('outcome', models.CharField(blank=True, choices=[('saved', 'Saved'), ('exported', 'Exported'), ('abandoned', 'Abandoned')], max_length=20, null=True)),
                ('fields_edited', models.JSONField(default=list)),
                ('edit_count', models.IntegerField(default=0)),
                ('time_to_first_edit', models.FloatField(blank=True, null=True)),
                ('crew_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='crew_sheets.crewsheet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='QualityAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('extraction_accuracy', models.FloatField(default=0.0)),
                ('data_completeness', models.FloatField(default=0.0)),
                ('format_consistency', models.FloatField(default=0.0)),
                ('issues_detected', models.JSONField(default=list)),
                ('validation_errors', models.JSONField(default=list)),
                ('assessed_at', models.DateTimeField(auto_now_add=True)),
                ('assessment_version', models.CharField(default='1.0', max_length=50)),
                ('crew_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_assessments', to='crew_sheets.crewsheet')),
            ],
            options={
                'ordering': ['-assessed_at'],
            },
        ),
        migrations.CreateModel(
            name='UserEdit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field_name', models.CharField(max_length=255)),
                ('employee_index', models.IntegerField(blank=True, null=True)),
                ('original_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('edit_type', models.CharField(default='field_edit', max_length=50)),
                ('edit_time_seconds', models.FloatField(default=0.0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edits', to='crew_sheets.extractionsession')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('common_cost_centers', models.JSONField(default=list)),
                ('common_tasks', models.JSONField(default=list)),
                ('typical_headers', models.JSONField(default=list)),
                ('frequently_edited_fields', models.JSONField(default=dict)),
                ('avg_session_duration', models.FloatField(default=0.0)),
                ('abandonment_rate', models.FloatField(default=0.0)),
                ('total_sheets_processed', models.IntegerField(default=0)),
                ('total_edits_made', models.IntegerField(default=0)),
                ('accuracy_improvement', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extraction_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FieldConfidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field_name', models.CharField(max_length=255)),
                ('employee_index', models.IntegerField(blank=True, null=True)),
                ('ocr_confidence', models.FloatField(default=0.0)),
                ('structure_confidence', models.FloatField(default=0.0)),
                ('data_consistency_score', models.FloatField(default=0.0)),
                ('historical_accuracy', models.FloatField(default=0.0)),
                ('overall_confidence', models.FloatField(default=0.0)),
                ('is_uncertain', models.BooleanField(default=False)),
                ('needs_review', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('crew_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_confidences', to='crew_sheets.crewsheet')),
            ],
            options={
                'unique_together': {('crew_sheet', 'field_name', 'employee_index')},
            },
        ),
    ]
