# Generated by Django 5.1.7 on 2025-07-24 22:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crew_sheets', '0002_crewsheet_confidence_score_crewsheet_needs_review_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromptVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_name', models.CharField(max_length=100)),
                ('prompt_content', models.TextField()),
                ('usage_count', models.IntegerField(default=0)),
                ('success_rate', models.FloatField(default=0.0)),
                ('avg_confidence', models.FloatField(default=0.0)),
                ('avg_edit_ratio', models.FloatField(default=0.0)),
                ('based_on_insights', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-success_rate', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SheetTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('company', models.CharField(blank=True, max_length=255)),
                ('template_image', models.ImageField(upload_to='templates/')),
                ('header_structure', models.JSONField()),
                ('expected_fields', models.JSONField()),
                ('template_type', models.CharField(choices=[('time_tracking', 'Time Tracking'), ('piece_work', 'Piece Work'), ('mixed', 'Mixed Time/Piece'), ('custom', 'Custom')], max_length=20)),
                ('usage_count', models.IntegerField(default=0)),
                ('success_rate', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-success_rate', '-usage_count'],
            },
        ),
        migrations.CreateModel(
            name='ExtractionExample',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('input_description', models.TextField()),
                ('extraction_result', models.JSONField()),
                ('user_corrections', models.JSONField(default=dict)),
                ('confidence_score', models.FloatField()),
                ('edit_ratio', models.FloatField()),
                ('user_satisfaction', models.FloatField(default=0.0)),
                ('embedding', models.JSONField(blank=True, null=True)),
                ('sheet_characteristics', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_high_quality', models.BooleanField(default=False)),
                ('crew_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crew_sheets.crewsheet')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crew_sheets.sheettemplate')),
            ],
            options={
                'ordering': ['-confidence_score', '-user_satisfaction'],
            },
        ),
        migrations.CreateModel(
            name='SmartReviewQueue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('priority_score', models.FloatField(default=0.0)),
                ('review_reason', models.CharField(choices=[('low_confidence', 'Low Confidence Score'), ('validation_failed', 'Validation Rules Failed'), ('unusual_format', 'Unusual Format Detected'), ('high_edit_frequency', 'High Edit Frequency Expected'), ('user_requested', 'User Requested Review'), ('template_mismatch', 'Template Mismatch')], max_length=30)),
                ('flagged_issues', models.JSONField(default=list)),
                ('suggested_actions', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_reviews', to=settings.AUTH_USER_MODEL)),
                ('crew_sheet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='crew_sheets.crewsheet')),
            ],
            options={
                'ordering': ['-priority_score', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CompanyLearningProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('company_domain', models.CharField(blank=True, max_length=100)),
                ('common_cost_centers', models.JSONField(default=list)),
                ('common_tasks', models.JSONField(default=list)),
                ('typical_headers', models.JSONField(default=list)),
                ('header_variations', models.JSONField(default=dict)),
                ('typical_start_times', models.JSONField(default=list)),
                ('typical_break_patterns', models.JSONField(default=list)),
                ('time_format_preferences', models.JSONField(default=dict)),
                ('employee_name_patterns', models.JSONField(default=dict)),
                ('common_job_codes', models.JSONField(default=list)),
                ('typical_hour_ranges', models.JSONField(default=dict)),
                ('sheets_processed', models.IntegerField(default=0)),
                ('accuracy_improvement', models.FloatField(default=0.0)),
                ('confidence_in_patterns', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'company_name')},
            },
        ),
    ]
