# Generated by Django 5.1.7 on 2025-07-29 22:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crew_sheets', '0003_promptversion_sheettemplate_extractionexample_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companylearningprofile',
            name='common_crew_names',
            field=models.JSONField(default=list),
        ),
        migrations.CreateModel(
            name='ExtractionHighlights',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('new_crew_names', models.JSONField(default=list)),
                ('new_cost_centers', models.JSONField(default=list)),
                ('new_tasks', models.JSONField(default=list)),
                ('highlight_metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('crew_sheet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='crew_sheets.crewsheet')),
            ],
        ),
    ]
