# Generated by Django 5.1.7 on 2025-07-29 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crew_sheets', '0004_companylearningprofile_common_crew_names_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheettemplate',
            name='expected_fields',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='sheettemplate',
            name='header_structure',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
